// mockups/SPEC.md: a per-screen skeleton extracted from the mockup HTML,
// so build reads a few lines per screen instead of the page. The model
// completes one Intent line per screen at the freeze; the rest is
// mechanical and regenerated. Regex extraction on purpose: no parser
// dependency, and mockups are plain HTML by the mockups skill's rules.
import { readdirSync, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { readIf } from './project.mjs';

const STATE_SUFFIX = /-(empty|error|loading)\.html$/;
const text = (html) => html.replace(/<[^>]+>/g, ' ').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/\s+/g, ' ').trim();
const uniq = (arr) => [...new Set(arr.filter(Boolean))];
const attr = (tag, name) => tag.match(new RegExp(`\\b${name}\\s*=\\s*"([^"]*)"`, 'i'))?.[1] ?? tag.match(new RegExp(`\\b${name}\\s*=\\s*'([^']*)'`, 'i'))?.[1] ?? null;

export function extractScreen(html) {
  const title = text(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] ?? '');
  const headings = uniq([...html.matchAll(/<h([1-3])[^>]*>([\s\S]*?)<\/h\1>/gi)].map((m) => text(m[2]))).slice(0, 12);
  const navHtml = [...html.matchAll(/<nav[^>]*>([\s\S]*?)<\/nav>/gi)].map((m) => m[1]).join('\n');
  const nav = uniq([...navHtml.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)].map((m) => `${text(m[2])} -> ${attr(m[1], 'href') ?? '?'}`)).slice(0, 12);
  const labels = new Map([...html.matchAll(/<label\b([^>]*)>([\s\S]*?)<\/label>/gi)].map((m) => [attr(m[1], 'for'), text(m[2])]));
  const fields = uniq([...html.matchAll(/<(input|select|textarea)\b([^>]*)>/gi)].map((m) => {
    const t = m[1].toLowerCase() === 'input' ? (attr(m[2], 'type') ?? 'text').toLowerCase() : m[1].toLowerCase();
    if (['hidden', 'submit', 'button', 'reset'].includes(t)) return null;
    const name = attr(m[2], 'name') ?? attr(m[2], 'id') ?? attr(m[2], 'placeholder') ?? '?';
    const label = labels.get(attr(m[2], 'id'));
    return `${label ? `${label} [${name}]` : name} (${t})`;
  })).slice(0, 20);
  const buttons = uniq([
    ...[...html.matchAll(/<button\b[^>]*>([\s\S]*?)<\/button>/gi)].map((m) => text(m[1])),
    ...[...html.matchAll(/<input\b([^>]*)>/gi)].filter((m) => /type\s*=\s*["'](submit|button)["']/i.test(m[1])).map((m) => attr(m[1], 'value'))
  ]).slice(0, 10);
  const columns = uniq([...html.matchAll(/<th\b[^>]*>([\s\S]*?)<\/th>/gi)].map((m) => text(m[1]))).slice(0, 12);
  const body = html.replace(/<nav[^>]*>[\s\S]*?<\/nav>/gi, '');
  const links = uniq([...body.matchAll(/<a\b([^>]*)>/gi)].map((m) => attr(m[1], 'href')).filter((h) => h && /\.html(#.*)?$/.test(h) && !h.startsWith('http'))).slice(0, 12);
  return { title, headings, nav, fields, buttons, columns, links };
}

export function screensIn(root) {
  const dir = join(root, 'mockups');
  if (!existsSync(dir)) return [];
  const files = readdirSync(dir).filter((f) => f.endsWith('.html') && f !== 'index.html').sort();
  const main = files.filter((f) => !STATE_SUFFIX.test(f));
  return main.map((f) => ({
    file: f,
    states: files.filter((s) => STATE_SUFFIX.test(s) && s.replace(STATE_SUFFIX, '') === f.replace(/\.html$/, ''))
  }));
}

// Sections of a spec file: "## <file>" followed by its lines.
export function specSections(spec) {
  const map = new Map();
  if (!spec) return map;
  for (const chunk of spec.split(/^## /m).slice(1)) {
    const [head, ...lines] = chunk.split('\n');
    map.set(head.trim(), lines.join('\n').trim());
  }
  return map;
}

export function existingIntents(spec) {
  const map = new Map();
  for (const [file, body] of specSections(spec)) {
    const intent = body.split('\n').find((l) => /^Intent:/.test(l));
    if (intent && !/<one line/.test(intent)) map.set(file, intent.trim());
  }
  return map;
}

export function renderSpec(root) {
  const screens = screensIn(root);
  const intents = existingIntents(readIf(join(root, 'mockups', 'SPEC.md')));
  const out = ['# Mockups spec', '', 'Generated by acdev mockup-spec from mockups/*.html; regenerate after a revision round. Only the Intent lines are written by hand, at the freeze. Build reads this file and opens a page only for the screen it is implementing.', ''];
  if (!screens.length) out.push('(no mockups/*.html found)');
  for (const s of screens) {
    const x = extractScreen(readIf(join(root, 'mockups', s.file)) ?? '');
    out.push(`## ${s.file}`);
    if (x.title) out.push(`Title: ${x.title}`);
    if (x.headings.length) out.push(`Headings: ${x.headings.join(' | ')}`);
    if (x.nav.length) out.push(`Nav: ${x.nav.join(' | ')}`);
    if (x.fields.length) out.push(`Fields: ${x.fields.join(' | ')}`);
    if (x.columns.length) out.push(`Columns: ${x.columns.join(' | ')}`);
    if (x.buttons.length) out.push(`Buttons: ${x.buttons.join(' | ')}`);
    if (x.links.length) out.push(`Links: ${x.links.join(', ')}`);
    if (s.states.length) out.push(`States: ${s.states.join(', ')}`);
    out.push(intents.get(s.file) ?? 'Intent: <one line: what the user does here and what must be true when it works; written at the freeze>', '');
  }
  return out.join('\n').trimEnd() + '\n';
}

export function writeSpec(root) {
  const spec = renderSpec(root);
  const path = join(root, 'mockups', 'SPEC.md');
  if (!existsSync(join(root, 'mockups'))) throw new Error('mockups/ not found');
  writeFileSync(path, spec);
  return { path: 'mockups/SPEC.md', screens: screensIn(root).length, chars: spec.length };
}
